spring.application.name=APIGateway
server.port=8061
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8000/eureka


#spring.cloud.gateway.server.webflux.routes[0].id=application1
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://Application1
#spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/get-info
#
#spring.cloud.gateway.server.webflux.routes[1].id=application2
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://Application2
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/get-data